FROM arm32v6/alpine:3.13

RUN apk update

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="oCIS Migration" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

COPY bin/ocis-migration /usr/bin/ocis-migration
